version: "3.7"
services:
  app:
    image: shire:latest
    build: {dockerfile: "Dockerfile", context: "./"}
    command: honcho start
    ports:
      - 5000:5000
    volumes:
      - .:/app
    env_file: .env
  cache:
    image: redis:5.0.6-alpine
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: frodo
      POSTGRES_PASSWORD: whereissam
      POSTGRES_DB: shire
    volumes:
      - ./data:/var/lib/postgresql/data
