---
- name: Install epel repo
  import_role:
    name: geerlingguy.repo-epel
  tags: [epel]

- name: Install ius repo
  import_role:
    name: linuxhq.ius
  vars:
    ius_repository_ius: true
  tags: [ius]

- name: Install pip3.6
  import_role:
    name: geerlingguy.pip
  vars:
    pip_package: python36u-pip
  tags: [pip]

- name: Install pip2
  import_role:
    name: geerlingguy.pip
  vars:
    pip_package: python-pip
  tags: [pip]

- name: Install supervisor
  import_role:
    name: geerlingguy.supervisor
  vars:
    supervisor_version: latest
    supervisor_started: true
    supervisor_enabled: true
    supervisor_config_path: /etc/supervisor
    supervisor_programs: []
    # TODO: add supervisor password
  tags: [supervisor]

- name: Deploy web
  import_role:
    name: ansistrano.deploy
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../../"
    ansistrano_deploy_to: /var/www/shire
    ansistrano_version_dir: releases
    ansistrano_current_dir: current
    ansistrano_current_via: symlink
    ansistrano_keep_releases: 5
    ansistrano_shared_paths: [venv3.6, ]
    ansistrano_shared_files: [.env, ]
    ansistrano_deploy_via: rsync
    ansistrano_after_setup_tasks_file: "{{ playbook_dir }}/roles/shire-{{ shire_entry }}/tasks/after-setup-tasks-file.yml"
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/roles/shire-{{ shire_entry }}/tasks/after-symlink-tasks-file.yml"
    ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/roles/shire-{{ shire_entry }}/tasks/after-symlink-shared-tasks-file.yml"
    # after setup: install sys deps, create venv
    # after code-updated: install python deps
    # after symlink: update supervisor conf, and reread, update.
    shire_entry: 'web'
    shire_supervisor_web_conf_path: /etc/supervisor/conf.d/shire-web.conf
    shire_supervisor_web_process_num: 4
    shire_process_user: shire
    shire_process_group: shire
    shire_port: 8000
  tags: [deploy]
