---
- name: Install epel repo
  import_role:
    name: geerlingguy.repo-epel
  tags: [epel]

- name: Install ius repo
  import_role:
    name: linuxhq.ius
  vars:
    ius_repository_ius: true
  tags: [ius]

- name: Install pip3.6
  import_role:
    name: geerlingguy.pip
  vars:
    pip_package: python36u-pip
  tags: [pip]

- name: Install pip2
  import_role:
    name: geerlingguy.pip
  vars:
    pip_package: python-pip
  tags: [pip]

- name: Install supervisor
  import_role:
    name: geerlingguy.supervisor
  vars:
    supervisor_version: latest
    supervisor_started: true
    supervisor_enabled: true
    supervisor_config_path: /etc/supervisor
    supervisor_programs: []
    # TODO: add supervisor password
  tags: [supervisor]

- name: Deploy app
  import_role:
    name: ansistrano.deploy
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../../"
    ansistrano_deploy_to: /var/www/shire
    ansistrano_version_dir: releases
    ansistrano_current_dir: current
    ansistrano_current_via: symlink
    ansistrano_keep_releases: 5
    ansistrano_deploy_via: rsync
    ansistrano_rsync_extra_params: "--exclude='.env' --exclude='.git' --exclude='venv'"
    # after setup: install sys deps, create venv
    # after code-updated: install python deps
    # after symlink: update supervisor conf, and reread, update.
  tags: [deploy]
