---
- hosts: lb
  pre_tasks:
    - name: Setup digitalocean credentials for certbot
      copy:
        content: "dns_digitalocean_token={{ lookup('env', 'DO_TOKEN') }}"
        dest: /root/.certbot-digitalocean.ini
        mode: 0600

    - name: Update epel repo
      yum:
        name:
          - epel-release
          - yum-utils
        state: present

    - name: Enable the optional channel
      command: yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional

    - name: Install Certbot DigitalOcean plugin
      yum:
        name:
          - python2-certbot-dns-digitalocean
        state: present
  roles:
    - role: geerlingguy.certbot
  vars:
    certbot_admin_email: "{{ lookup('env', 'CERTBOT_ADMIN_EMAIL') }}"
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services: []
    certbot_create_method: standalone
    certbot_certs:
      - domains: ["{{ lookup('env', 'SITE_DOMAIN') }}", "*.{{ lookup('env', 'SITE_DOMAIN') }}"]
    certbot_create_command: "certbot certonly --noninteractive --dns-digitalocean --dns-digitalocean-credentials=/root/.certbot-digitalocean.ini --dns-digitalocean-propagation-seconds=60 --agree-tos --email {{ cert_item.email | default(certbot_admin_email) }} -d {{ cert_item.domains | join(',') }}"
