---
- hosts: lb
  roles:
    - role: roles/lb
  vars:
    site_domain: "{{ lookup('env', 'SITE_DOMAIN') }}"
    letsencrypt_state_dir: "{{ lookup('env', 'LETSENCRYPT_STATE_DIR') }}"
    letsencrypt_backup_dir: "{{ lookup('env', 'LETSENCRYPT_BACKUP_DIR') }}"
    certbot_admin_email: "{{ lookup('env', 'CERTBOT_ADMIN_EMAIL') }}"
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services: []
    certbot_create_method: standalone
    certbot_certs:
      - domains: ["{{ lookup('env', 'SITE_DOMAIN') }}", "*.{{ lookup('env', 'SITE_DOMAIN') }}"]
    certbot_create_command: "certbot certonly --noninteractive --dns-digitalocean --dns-digitalocean-credentials=/root/.certbot-digitalocean.ini --dns-digitalocean-propagation-seconds=60 --agree-tos --email {{ cert_item.email | default(certbot_admin_email) }} -d {{ cert_item.domains | join(',') }}"
    nginx_http_template_enable: true
    nginx_http_template:
      shire80:
        template_file: http/default.conf.j2
        conf_file_name: shire-80.conf
        conf_file_location: /etc/nginx/conf.d/
        port: 80
        server_name: "{{ lookup('env', 'SITE_DOMAIN') }}"
        https_redirect: true
      shire443:
        template_file: shire-443.conf.j2
        conf_file_name: shire-443.conf
