---
- hosts: prom
  roles:
    - role: cloudalchemy.prometheus
      tags: ["prometheus"]
    - role: cloudalchemy.grafana
      tags: ["grafana"]
  vars:
    prometheus_targets:
      node:
        - targets:
            # TODO: parse env.SITE_INVENTORY_SPEC and set it dynamically.
            - frodo.sfo2.svr.marksth.fun:9100
          labels:
            env: production
    grafana_security:
      admin_user: "{{ lookup('env', 'GRAFANA_ADMIN_USER') }}"
      admin_password: "{{ lookup('env', 'GRAFANA_ADMIN_PASSWORD') }}"
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://{{ prometheus_web_listen_address }}'
        basicAuth: false
