- name: Wait for target connection to become reachable/usable
  wait_for_connection:

- name: Download juicefs CLI
  get_url:
    url: "{{jfs_download_url}}"
    mode: 0755
    dest: "{{jfs_bin}}"

- name: Get authenticated with juicefs meta server
  command: "{{jfs_bin}} auth {{jfs_name}} --token {{jfs_token}} --accesskey {{jfs_bucket_accesskey}} --secretkey {{jfs_bucket_secretkey}} --bucket {{jfs_bucket_name}}"
  args:
    creates: /root/.juicefs/{{jfs_name}}.conf

- name: Mount juicefs using FUSE
  mount:
    path: "{{jfs_path}}"
    src: "{{jfs_name}}"
    fstype: juicefs
    opts: _netdev
    state: mounted
