---
- name: Setup digitalocean credentials for certbot
  copy:
    content: "dns_digitalocean_token={{ lookup('env', 'DO_TOKEN') }}"
    dest: /root/.certbot-digitalocean.ini
    mode: 0600
  tags: [certbot]

- name: Update epel repo
  yum:
    name:
      - epel-release
      - yum-utils
    state: present
  tags: [certbot]

- name: Enable the optional channel
  command: yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional
  tags: [certbot]

- name: Install Certbot DigitalOcean plugin
  yum:
    name:
      - python2-certbot-dns-digitalocean
    state: present
  tags: [certbot]

- name: Run certbot
  import_role:
    name: geerlingguy.certbot
  tags: [certbot]

- name: Run nginx
  import_role:
    name: nginxinc.nginx
  tags: [nginx]
